package org.fossify.voicerecorder.transcription

/**
 * The complete set of languages whisper supports, as (code -> English name).
 * Used to populate the transcription-language picker. No language is special-cased.
 */
object WhisperLanguages {
    // Order here is irrelevant; the picker sorts by display name.
    val ALL: List<Pair<String, String>> = listOf(
        "af" to "Afrikaans",
        "am" to "Amharic",
        "ar" to "Arabic",
        "as" to "Assamese",
        "az" to "Azerbaijani",
        "ba" to "Bashkir",
        "be" to "Belarusian",
        "bg" to "Bulgarian",
        "bn" to "Bengali",
        "bo" to "Tibetan",
        "br" to "Breton",
        "bs" to "Bosnian",
        "ca" to "Catalan",
        "cs" to "Czech",
        "cy" to "Welsh",
        "da" to "Danish",
        "de" to "German",
        "el" to "Greek",
        "en" to "English",
        "es" to "Spanish",
        "et" to "Estonian",
        "eu" to "Basque",
        "fa" to "Persian",
        "fi" to "Finnish",
        "fo" to "Faroese",
        "fr" to "French",
        "gl" to "Galician",
        "gu" to "Gujarati",
        "ha" to "Hausa",
        "haw" to "Hawaiian",
        "he" to "Hebrew",
        "hi" to "Hindi",
        "hr" to "Croatian",
        "ht" to "Haitian Creole",
        "hu" to "Hungarian",
        "hy" to "Armenian",
        "id" to "Indonesian",
        "is" to "Icelandic",
        "it" to "Italian",
        "ja" to "Japanese",
        "jw" to "Javanese",
        "ka" to "Georgian",
        "kk" to "Kazakh",
        "km" to "Khmer",
        "kn" to "Kannada",
        "ko" to "Korean",
        "la" to "Latin",
        "lb" to "Luxembourgish",
        "ln" to "Lingala",
        "lo" to "Lao",
        "lt" to "Lithuanian",
        "lv" to "Latvian",
        "mg" to "Malagasy",
        "mi" to "Maori",
        "mk" to "Macedonian",
        "ml" to "Malayalam",
        "mn" to "Mongolian",
        "mr" to "Marathi",
        "ms" to "Malay",
        "mt" to "Maltese",
        "my" to "Myanmar",
        "ne" to "Nepali",
        "nl" to "Dutch",
        "nn" to "Nynorsk",
        "no" to "Norwegian",
        "oc" to "Occitan",
        "pa" to "Punjabi",
        "pl" to "Polish",
        "ps" to "Pashto",
        "pt" to "Portuguese",
        "ro" to "Romanian",
        "ru" to "Russian",
        "sa" to "Sanskrit",
        "sd" to "Sindhi",
        "si" to "Sinhala",
        "sk" to "Slovak",
        "sl" to "Slovenian",
        "sn" to "Shona",
        "so" to "Somali",
        "sq" to "Albanian",
        "sr" to "Serbian",
        "su" to "Sundanese",
        "sv" to "Swedish",
        "sw" to "Swahili",
        "ta" to "Tamil",
        "te" to "Telugu",
        "tg" to "Tajik",
        "th" to "Thai",
        "tk" to "Turkmen",
        "tl" to "Tagalog",
        "tr" to "Turkish",
        "tt" to "Tatar",
        "uk" to "Ukrainian",
        "ur" to "Urdu",
        "uz" to "Uzbek",
        "vi" to "Vietnamese",
        "yi" to "Yiddish",
        "yo" to "Yoruba",
        "yue" to "Cantonese",
        "zh" to "Chinese",
    )

    private val codeToName: Map<String, String> = ALL.toMap()

    // Display names sorted alphabetically, paired with their codes — for the picker.
    val SORTED_BY_NAME: List<Pair<String, String>> = ALL.sortedBy { it.second }

    fun nameOf(code: String): String = codeToName[code] ?: code
}
